### ISSUE TITLE
字條數量

### ISSUE THREAD

**Issue by TNTErick** [danny0838/handict#1]
我數了一下，一共有 75657條資料。庫典寫共有 71255 字。想問剩下字條的來源是？

**Comment by danny0838** [comment]
都是從漢文庫典網站抓下來的。你說的狀況應該是有些項目 id 重複導致，即有多組編碼共用一個 id。

**Comment by TNTErick** [comment]
多組編碼是指什麼情況？
另外問，有倉六重碼但其他不同的字條嗎？去掉倉六同碼之後僅剩71 184條，如旲（日大）字卽在庫典中而貴資料庫未収。

**Comment by danny0838** [comment]
> 多組編碼是指什麼情況？

就是字面意思，一個 id 對應多組編碼。

> 另外問，有倉六重碼但其他不同的字條嗎？

不懂你的問題。而且你應該可以從資料庫找出答案。

> 去掉倉六同碼之後僅剩71 184條，如旲（日大）字卽在庫典中而貴資料庫未収。

這就不清楚了，本資料檔是舊漢文庫典關閉前爬來的，當時可能有些頁面無法連上。現在能看到當然可以以最新版為準。

**Comment by TNTErick** [comment]
謝謝。

**Comment by danny0838** [comment]
已補錄闕漏的資料。
